### PR TITLE
fix random page flickering on page load #256

### LINKED ISSUE #256: Random quotes for 404 page flickers
If you land to **404 not found page** in learn site,[ https://learn.freecodecamp.org/404]( https://learn.freecodecamp.org/404) , It will show the 404 image and a random quote. As soon as you start reading the quote it changes to another quote !
It appears due to some bug, page is showing one quote first, then randomly selecting another quote after 1 second. Bad user experience.
ozklrhjojw

### PR DESCRIPTION
**Pull request by wadleo**
Change the 404 page react stateless component to a pure component to prevent quote changes on load. 
Fixes #256

### CODE REVIEW

**Comment by Bouncey** [comment]
Now when the static page is built, we don't have a quote but the flicker is still there when the react app takes over.

Instead of rendering an empty quote, or a quopte that we know is going to change, we should just render a loader like `ball-clip-rotate-multiple` from [`react-spinkit`](http://kyleamathews.github.io/react-spinkit/) with a color of `#006400`


fourohfour

File: src/pages/404.js [hunk 1]
```diff
@@ -6,28 +6,55 @@ import './404.css';
 import notFoundLogo from '../../static/img/freeCodeCamp-404.svg';
 import { quotes } from '../../static/json/quotes.json';
 
-let randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
+var Spinner = require('react-spinkit');
```
Comment (Bouncey) [inline src/pages/404.js]: It is generally a good idea to keep the same import convention within the same file. Also, this type of multiple import stratergies is not supported in `gatsby` v2, which we are working towards on a separate branch.

Please use 
```js
import Spinner from 'react-spinkit';
```

As this import is from npm, please place it under the `gatsby-link` import above.

File: src/pages/404.js [hunk 2]
```diff
@@ -6,28 +6,55 @@ import './404.css';
...
+let randomQuote: any;
```
Comment (Bouncey) [inline src/pages/404.js]: We are not using typeScript/flow in this project. Seeing as you are now using a component, it would be better to store the quote in component state.

File: src/pages/404.js [hunk 3]
```diff
@@ -6,28 +6,55 @@ import './404.css';
...
+  }
 
-    <img alt='learn to code at freeCodeCamp 404' src={notFoundLogo} />
-    <h1>NOT FOUND</h1>
-    <p>We couldn't find what you were looking for, but here is a quote:</p>
+  render() {
+    if (randomQuote !== undefined) {
+      return (
+        <div className='notfound-page-wrapper'>
+          <Helmet title='Page Not Found | freeCodeCamp' />
```
Comment (Bouncey) [inline src/pages/404.js]: There is some repartion here that we can remove. Consider this

```jsx
render() {
  return (
    <div className='notfound-page-wrapper'>
      <Helmet title='Page Not Found | freeCodeCamp' />
      <img alt='learn to code at freeCodeCamp 404' src={notFoundLogo} />
      <h1>NOT FOUND</h1>
      {
        this.state.randomQuote ? (
          <div>
            <p>
              We couldn&#x27;t find what you were looking for, but here is a
              quote:
            </p>
            <div className='quote-wrapper'>
              <p className='quote'>
                <span>&#8220;</span>
                {randomQuote.quote}
              </p>
              <p className='author'>- {randomQuote.author}</p>
            </div>
          </div>
        ) : (
          <Spinner />
        )
      }
      <Link className='btn-curriculum' to='/'>
        View the Curriculum
      </Link>
    </div>
  );
}
```

File: src/pages/404.js (hunk 2 above)
Comment (wadleo) [reply src/pages/404.js]: okay

Comment (Bouncey) [reply src/pages/404.js]: In a normal react app yes, but the way Gatsby works is it when it builds the site, it renders each page and then writes the html to a file.

In our case, whatever the random quote is when Gatsby renders the page, it is that quite that users will see for a brief moment until the client side app starts and generates a new random quote. 

We want to take the randomness away from when Gatsby is building the site so the initial page load isn't so disorienting for users.

Comment (wadleo) [reply src/pages/404.js]: Since I can't update the state in the componentDidMount method as per the rules set for TravisCI, I would recommend we leave the randomQuote variable out the state of the component. Let me know what you think.

**Comment by wadleo** [comment]
Hi @Bouncey, can you review this and let know if it's ok now, thanks.

**Comment by raisedadead** [comment]
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @wadleo Nice work.

Happy Contributing!
